// TRY - CATCH

const num1 = 20;
const num2 = 30

console.log(num1);
try {
	console.log(num3);
} catch (ex) {
	console.log(ex);
}
console.log(num2);
